const std = @import("std");

const fractional_scale_v1 = @import("fractional_scale_v1.zig");
const xdg_activation_v1 = @import("xdg_activation_v1.zig");
const pointer_constraints_unstable_v1 = @import("pointer_constraints_unstable_v1.zig");
const xdg_decoration_unstable_v1 = @import("xdg_decoration_unstable_v1.zig");
const input_timestamps_unstable_v1 = @import("input_timestamps_unstable_v1.zig");
const xwayland_shell_v1 = @import("xwayland_shell_v1.zig");
const ext_session_lock_v1 = @import("ext_session_lock_v1.zig");
const xdg_toplevel_drag_v1 = @import("xdg_toplevel_drag_v1.zig");
const presentation_time = @import("presentation_time.zig");
const keyboard_shortcuts_inhibit_unstable_v1 = @import("keyboard_shortcuts_inhibit_unstable_v1.zig");
const cursor_shape_v1 = @import("cursor_shape_v1.zig");
const ext_image_copy_capture_v1 = @import("ext_image_copy_capture_v1.zig");
const drm_lease_v1 = @import("drm_lease_v1.zig");
const xdg_toplevel_icon_v1 = @import("xdg_toplevel_icon_v1.zig");
const linux_drm_syncobj_v1 = @import("linux_drm_syncobj_v1.zig");
const input_method_unstable_v1 = @import("input_method_unstable_v1.zig");
const xdg_shell = @import("xdg_shell.zig");
const xdg_output_unstable_v1 = @import("xdg_output_unstable_v1.zig");
const text_input_unstable_v3 = @import("text_input_unstable_v3.zig");
const fifo_v1 = @import("fifo_v1.zig");
const xdg_dialog_v1 = @import("xdg_dialog_v1.zig");
const text_input_unstable_v1 = @import("text_input_unstable_v1.zig");
const tablet_v2 = @import("tablet_v2.zig");
const ext_foreign_toplevel_list_v1 = @import("ext_foreign_toplevel_list_v1.zig");
const viewporter = @import("viewporter.zig");
const content_type_v1 = @import("content_type_v1.zig");
const fullscreen_shell_unstable_v1 = @import("fullscreen_shell_unstable_v1.zig");
const ext_idle_notify_v1 = @import("ext_idle_notify_v1.zig");
const wayland = @import("wayland.zig");
const commit_timing_v1 = @import("commit_timing_v1.zig");
const tearing_control_v1 = @import("tearing_control_v1.zig");
const ext_image_capture_source_v1 = @import("ext_image_capture_source_v1.zig");
const wp_primary_selection_unstable_v1 = @import("wp_primary_selection_unstable_v1.zig");
const zwp_linux_explicit_synchronization_unstable_v1 = @import("zwp_linux_explicit_synchronization_unstable_v1.zig");
const alpha_modifier_v1 = @import("alpha_modifier_v1.zig");
const xdg_foreign_unstable_v1 = @import("xdg_foreign_unstable_v1.zig");
const relative_pointer_unstable_v1 = @import("relative_pointer_unstable_v1.zig");
const xwayland_keyboard_grab_unstable_v1 = @import("xwayland_keyboard_grab_unstable_v1.zig");
const linux_dmabuf_v1 = @import("linux_dmabuf_v1.zig");
const security_context_v1 = @import("security_context_v1.zig");
const idle_inhibit_unstable_v1 = @import("idle_inhibit_unstable_v1.zig");
const xdg_foreign_unstable_v2 = @import("xdg_foreign_unstable_v2.zig");
const single_pixel_buffer_v1 = @import("single_pixel_buffer_v1.zig");
const ext_transient_seat_v1 = @import("ext_transient_seat_v1.zig");
const xdg_system_bell_v1 = @import("xdg_system_bell_v1.zig");
const pointer_gestures_unstable_v1 = @import("pointer_gestures_unstable_v1.zig");

pub const types = @import("types.zig");

pub const Interface = enum {
    invalid,
    wl_display,
    wl_registry,
    wl_callback,
    wl_compositor,
    wl_shm_pool,
    wl_shm,
    wl_buffer,
    wl_data_offer,
    wl_data_source,
    wl_data_device,
    wl_data_device_manager,
    wl_shell,
    wl_shell_surface,
    wl_surface,
    wl_seat,
    wl_pointer,
    wl_keyboard,
    wl_touch,
    wl_output,
    wl_region,
    wl_subcompositor,
    wl_subsurface,
    zwp_linux_dmabuf_v1,
    zwp_linux_buffer_params_v1,
    zwp_linux_dmabuf_feedback_v1,
    wp_presentation,
    wp_presentation_feedback,
    zwp_tablet_manager_v2,
    zwp_tablet_seat_v2,
    zwp_tablet_tool_v2,
    zwp_tablet_v2,
    zwp_tablet_pad_ring_v2,
    zwp_tablet_pad_strip_v2,
    zwp_tablet_pad_group_v2,
    zwp_tablet_pad_v2,
    wp_viewporter,
    wp_viewport,
    xdg_wm_base,
    xdg_positioner,
    xdg_surface,
    xdg_toplevel,
    xdg_popup,
    wp_alpha_modifier_v1,
    wp_alpha_modifier_surface_v1,
    wp_content_type_manager_v1,
    wp_content_type_v1,
    wp_cursor_shape_manager_v1,
    wp_cursor_shape_device_v1,
    wp_drm_lease_device_v1,
    wp_drm_lease_connector_v1,
    wp_drm_lease_request_v1,
    wp_drm_lease_v1,
    ext_foreign_toplevel_list_v1,
    ext_foreign_toplevel_handle_v1,
    ext_idle_notifier_v1,
    ext_idle_notification_v1,
    ext_session_lock_manager_v1,
    ext_session_lock_v1,
    ext_session_lock_surface_v1,
    ext_transient_seat_manager_v1,
    ext_transient_seat_v1,
    wp_fractional_scale_manager_v1,
    wp_fractional_scale_v1,
    wp_linux_drm_syncobj_manager_v1,
    wp_linux_drm_syncobj_timeline_v1,
    wp_linux_drm_syncobj_surface_v1,
    wp_security_context_manager_v1,
    wp_security_context_v1,
    wp_single_pixel_buffer_manager_v1,
    wp_tearing_control_manager_v1,
    wp_tearing_control_v1,
    xdg_activation_v1,
    xdg_activation_token_v1,
    xdg_wm_dialog_v1,
    xdg_dialog_v1,
    xdg_toplevel_drag_manager_v1,
    xdg_toplevel_drag_v1,
    xwayland_shell_v1,
    xwayland_surface_v1,
    ext_image_capture_source_v1,
    ext_output_image_capture_source_manager_v1,
    ext_foreign_toplevel_image_capture_source_manager_v1,
    ext_image_copy_capture_manager_v1,
    ext_image_copy_capture_session_v1,
    ext_image_copy_capture_frame_v1,
    ext_image_copy_capture_cursor_session_v1,
    xdg_toplevel_icon_manager_v1,
    xdg_toplevel_icon_v1,
    wp_commit_timing_manager_v1,
    wp_commit_timer_v1,
    wp_fifo_manager_v1,
    wp_fifo_v1,
    xdg_system_bell_v1,
    zwp_fullscreen_shell_v1,
    zwp_fullscreen_shell_mode_feedback_v1,
    zwp_idle_inhibit_manager_v1,
    zwp_idle_inhibitor_v1,
    zwp_input_method_context_v1,
    zwp_input_method_v1,
    zwp_input_panel_v1,
    zwp_input_panel_surface_v1,
    zwp_input_timestamps_manager_v1,
    zwp_input_timestamps_v1,
    zwp_keyboard_shortcuts_inhibit_manager_v1,
    zwp_keyboard_shortcuts_inhibitor_v1,
    zwp_linux_explicit_synchronization_v1,
    zwp_linux_surface_synchronization_v1,
    zwp_linux_buffer_release_v1,
    zwp_pointer_constraints_v1,
    zwp_locked_pointer_v1,
    zwp_confined_pointer_v1,
    zwp_pointer_gestures_v1,
    zwp_pointer_gesture_swipe_v1,
    zwp_pointer_gesture_pinch_v1,
    zwp_pointer_gesture_hold_v1,
    zwp_primary_selection_device_manager_v1,
    zwp_primary_selection_device_v1,
    zwp_primary_selection_offer_v1,
    zwp_primary_selection_source_v1,
    zwp_relative_pointer_manager_v1,
    zwp_relative_pointer_v1,
    zwp_text_input_v1,
    zwp_text_input_manager_v1,
    zwp_text_input_v3,
    zwp_text_input_manager_v3,
    zxdg_decoration_manager_v1,
    zxdg_toplevel_decoration_v1,
    zxdg_exporter_v1,
    zxdg_importer_v1,
    zxdg_exported_v1,
    zxdg_imported_v1,
    zxdg_exporter_v2,
    zxdg_importer_v2,
    zxdg_exported_v2,
    zxdg_imported_v2,
    zxdg_output_manager_v1,
    zxdg_output_v1,
    zwp_xwayland_keyboard_grab_manager_v1,
    zwp_xwayland_keyboard_grab_v1,
};

pub const Requests = union(Interface) {
    invalid: std.EnumArray(enum {}, ?*const fn (u32, enum {}, *anyopaque) void),
    wl_display: std.EnumArray(wayland.display.request, ?*const fn (u32, wayland.display.request, *anyopaque) void),
    wl_registry: std.EnumArray(wayland.registry.request, ?*const fn (u32, wayland.registry.request, *anyopaque) void),
    wl_callback: std.EnumArray(wayland.callback.request, ?*const fn (u32, wayland.callback.request, *anyopaque) void),
    wl_compositor: std.EnumArray(wayland.compositor.request, ?*const fn (u32, wayland.compositor.request, *anyopaque) void),
    wl_shm_pool: std.EnumArray(wayland.shm_pool.request, ?*const fn (u32, wayland.shm_pool.request, *anyopaque) void),
    wl_shm: std.EnumArray(wayland.shm.request, ?*const fn (u32, wayland.shm.request, *anyopaque) void),
    wl_buffer: std.EnumArray(wayland.buffer.request, ?*const fn (u32, wayland.buffer.request, *anyopaque) void),
    wl_data_offer: std.EnumArray(wayland.data_offer.request, ?*const fn (u32, wayland.data_offer.request, *anyopaque) void),
    wl_data_source: std.EnumArray(wayland.data_source.request, ?*const fn (u32, wayland.data_source.request, *anyopaque) void),
    wl_data_device: std.EnumArray(wayland.data_device.request, ?*const fn (u32, wayland.data_device.request, *anyopaque) void),
    wl_data_device_manager: std.EnumArray(wayland.data_device_manager.request, ?*const fn (u32, wayland.data_device_manager.request, *anyopaque) void),
    wl_shell: std.EnumArray(wayland.shell.request, ?*const fn (u32, wayland.shell.request, *anyopaque) void),
    wl_shell_surface: std.EnumArray(wayland.shell_surface.request, ?*const fn (u32, wayland.shell_surface.request, *anyopaque) void),
    wl_surface: std.EnumArray(wayland.surface.request, ?*const fn (u32, wayland.surface.request, *anyopaque) void),
    wl_seat: std.EnumArray(wayland.seat.request, ?*const fn (u32, wayland.seat.request, *anyopaque) void),
    wl_pointer: std.EnumArray(wayland.pointer.request, ?*const fn (u32, wayland.pointer.request, *anyopaque) void),
    wl_keyboard: std.EnumArray(wayland.keyboard.request, ?*const fn (u32, wayland.keyboard.request, *anyopaque) void),
    wl_touch: std.EnumArray(wayland.touch.request, ?*const fn (u32, wayland.touch.request, *anyopaque) void),
    wl_output: std.EnumArray(wayland.output.request, ?*const fn (u32, wayland.output.request, *anyopaque) void),
    wl_region: std.EnumArray(wayland.region.request, ?*const fn (u32, wayland.region.request, *anyopaque) void),
    wl_subcompositor: std.EnumArray(wayland.subcompositor.request, ?*const fn (u32, wayland.subcompositor.request, *anyopaque) void),
    wl_subsurface: std.EnumArray(wayland.subsurface.request, ?*const fn (u32, wayland.subsurface.request, *anyopaque) void),
    zwp_linux_dmabuf_v1: std.EnumArray(linux_dmabuf_v1.linux_dmabuf_v1.request, ?*const fn (u32, linux_dmabuf_v1.linux_dmabuf_v1.request, *anyopaque) void),
    zwp_linux_buffer_params_v1: std.EnumArray(linux_dmabuf_v1.linux_buffer_params_v1.request, ?*const fn (u32, linux_dmabuf_v1.linux_buffer_params_v1.request, *anyopaque) void),
    zwp_linux_dmabuf_feedback_v1: std.EnumArray(linux_dmabuf_v1.linux_dmabuf_feedback_v1.request, ?*const fn (u32, linux_dmabuf_v1.linux_dmabuf_feedback_v1.request, *anyopaque) void),
    wp_presentation: std.EnumArray(presentation_time.presentation.request, ?*const fn (u32, presentation_time.presentation.request, *anyopaque) void),
    wp_presentation_feedback: std.EnumArray(presentation_time.presentation_feedback.request, ?*const fn (u32, presentation_time.presentation_feedback.request, *anyopaque) void),
    zwp_tablet_manager_v2: std.EnumArray(tablet_v2.tablet_manager_v2.request, ?*const fn (u32, tablet_v2.tablet_manager_v2.request, *anyopaque) void),
    zwp_tablet_seat_v2: std.EnumArray(tablet_v2.tablet_seat_v2.request, ?*const fn (u32, tablet_v2.tablet_seat_v2.request, *anyopaque) void),
    zwp_tablet_tool_v2: std.EnumArray(tablet_v2.tablet_tool_v2.request, ?*const fn (u32, tablet_v2.tablet_tool_v2.request, *anyopaque) void),
    zwp_tablet_v2: std.EnumArray(tablet_v2.tablet_v2.request, ?*const fn (u32, tablet_v2.tablet_v2.request, *anyopaque) void),
    zwp_tablet_pad_ring_v2: std.EnumArray(tablet_v2.tablet_pad_ring_v2.request, ?*const fn (u32, tablet_v2.tablet_pad_ring_v2.request, *anyopaque) void),
    zwp_tablet_pad_strip_v2: std.EnumArray(tablet_v2.tablet_pad_strip_v2.request, ?*const fn (u32, tablet_v2.tablet_pad_strip_v2.request, *anyopaque) void),
    zwp_tablet_pad_group_v2: std.EnumArray(tablet_v2.tablet_pad_group_v2.request, ?*const fn (u32, tablet_v2.tablet_pad_group_v2.request, *anyopaque) void),
    zwp_tablet_pad_v2: std.EnumArray(tablet_v2.tablet_pad_v2.request, ?*const fn (u32, tablet_v2.tablet_pad_v2.request, *anyopaque) void),
    wp_viewporter: std.EnumArray(viewporter.viewporter.request, ?*const fn (u32, viewporter.viewporter.request, *anyopaque) void),
    wp_viewport: std.EnumArray(viewporter.viewport.request, ?*const fn (u32, viewporter.viewport.request, *anyopaque) void),
    xdg_wm_base: std.EnumArray(xdg_shell.wm_base.request, ?*const fn (u32, xdg_shell.wm_base.request, *anyopaque) void),
    xdg_positioner: std.EnumArray(xdg_shell.positioner.request, ?*const fn (u32, xdg_shell.positioner.request, *anyopaque) void),
    xdg_surface: std.EnumArray(xdg_shell.surface.request, ?*const fn (u32, xdg_shell.surface.request, *anyopaque) void),
    xdg_toplevel: std.EnumArray(xdg_shell.toplevel.request, ?*const fn (u32, xdg_shell.toplevel.request, *anyopaque) void),
    xdg_popup: std.EnumArray(xdg_shell.popup.request, ?*const fn (u32, xdg_shell.popup.request, *anyopaque) void),
    wp_alpha_modifier_v1: std.EnumArray(alpha_modifier_v1.alpha_modifier_v1.request, ?*const fn (u32, alpha_modifier_v1.alpha_modifier_v1.request, *anyopaque) void),
    wp_alpha_modifier_surface_v1: std.EnumArray(alpha_modifier_v1.alpha_modifier_surface_v1.request, ?*const fn (u32, alpha_modifier_v1.alpha_modifier_surface_v1.request, *anyopaque) void),
    wp_content_type_manager_v1: std.EnumArray(content_type_v1.content_type_manager_v1.request, ?*const fn (u32, content_type_v1.content_type_manager_v1.request, *anyopaque) void),
    wp_content_type_v1: std.EnumArray(content_type_v1.content_type_v1.request, ?*const fn (u32, content_type_v1.content_type_v1.request, *anyopaque) void),
    wp_cursor_shape_manager_v1: std.EnumArray(cursor_shape_v1.cursor_shape_manager_v1.request, ?*const fn (u32, cursor_shape_v1.cursor_shape_manager_v1.request, *anyopaque) void),
    wp_cursor_shape_device_v1: std.EnumArray(cursor_shape_v1.cursor_shape_device_v1.request, ?*const fn (u32, cursor_shape_v1.cursor_shape_device_v1.request, *anyopaque) void),
    wp_drm_lease_device_v1: std.EnumArray(drm_lease_v1.drm_lease_device_v1.request, ?*const fn (u32, drm_lease_v1.drm_lease_device_v1.request, *anyopaque) void),
    wp_drm_lease_connector_v1: std.EnumArray(drm_lease_v1.drm_lease_connector_v1.request, ?*const fn (u32, drm_lease_v1.drm_lease_connector_v1.request, *anyopaque) void),
    wp_drm_lease_request_v1: std.EnumArray(drm_lease_v1.drm_lease_request_v1.request, ?*const fn (u32, drm_lease_v1.drm_lease_request_v1.request, *anyopaque) void),
    wp_drm_lease_v1: std.EnumArray(drm_lease_v1.drm_lease_v1.request, ?*const fn (u32, drm_lease_v1.drm_lease_v1.request, *anyopaque) void),
    ext_foreign_toplevel_list_v1: std.EnumArray(ext_foreign_toplevel_list_v1.foreign_toplevel_list_v1.request, ?*const fn (u32, ext_foreign_toplevel_list_v1.foreign_toplevel_list_v1.request, *anyopaque) void),
    ext_foreign_toplevel_handle_v1: std.EnumArray(ext_foreign_toplevel_list_v1.foreign_toplevel_handle_v1.request, ?*const fn (u32, ext_foreign_toplevel_list_v1.foreign_toplevel_handle_v1.request, *anyopaque) void),
    ext_idle_notifier_v1: std.EnumArray(ext_idle_notify_v1.idle_notifier_v1.request, ?*const fn (u32, ext_idle_notify_v1.idle_notifier_v1.request, *anyopaque) void),
    ext_idle_notification_v1: std.EnumArray(ext_idle_notify_v1.idle_notification_v1.request, ?*const fn (u32, ext_idle_notify_v1.idle_notification_v1.request, *anyopaque) void),
    ext_session_lock_manager_v1: std.EnumArray(ext_session_lock_v1.session_lock_manager_v1.request, ?*const fn (u32, ext_session_lock_v1.session_lock_manager_v1.request, *anyopaque) void),
    ext_session_lock_v1: std.EnumArray(ext_session_lock_v1.session_lock_v1.request, ?*const fn (u32, ext_session_lock_v1.session_lock_v1.request, *anyopaque) void),
    ext_session_lock_surface_v1: std.EnumArray(ext_session_lock_v1.session_lock_surface_v1.request, ?*const fn (u32, ext_session_lock_v1.session_lock_surface_v1.request, *anyopaque) void),
    ext_transient_seat_manager_v1: std.EnumArray(ext_transient_seat_v1.transient_seat_manager_v1.request, ?*const fn (u32, ext_transient_seat_v1.transient_seat_manager_v1.request, *anyopaque) void),
    ext_transient_seat_v1: std.EnumArray(ext_transient_seat_v1.transient_seat_v1.request, ?*const fn (u32, ext_transient_seat_v1.transient_seat_v1.request, *anyopaque) void),
    wp_fractional_scale_manager_v1: std.EnumArray(fractional_scale_v1.fractional_scale_manager_v1.request, ?*const fn (u32, fractional_scale_v1.fractional_scale_manager_v1.request, *anyopaque) void),
    wp_fractional_scale_v1: std.EnumArray(fractional_scale_v1.fractional_scale_v1.request, ?*const fn (u32, fractional_scale_v1.fractional_scale_v1.request, *anyopaque) void),
    wp_linux_drm_syncobj_manager_v1: std.EnumArray(linux_drm_syncobj_v1.linux_drm_syncobj_manager_v1.request, ?*const fn (u32, linux_drm_syncobj_v1.linux_drm_syncobj_manager_v1.request, *anyopaque) void),
    wp_linux_drm_syncobj_timeline_v1: std.EnumArray(linux_drm_syncobj_v1.linux_drm_syncobj_timeline_v1.request, ?*const fn (u32, linux_drm_syncobj_v1.linux_drm_syncobj_timeline_v1.request, *anyopaque) void),
    wp_linux_drm_syncobj_surface_v1: std.EnumArray(linux_drm_syncobj_v1.linux_drm_syncobj_surface_v1.request, ?*const fn (u32, linux_drm_syncobj_v1.linux_drm_syncobj_surface_v1.request, *anyopaque) void),
    wp_security_context_manager_v1: std.EnumArray(security_context_v1.security_context_manager_v1.request, ?*const fn (u32, security_context_v1.security_context_manager_v1.request, *anyopaque) void),
    wp_security_context_v1: std.EnumArray(security_context_v1.security_context_v1.request, ?*const fn (u32, security_context_v1.security_context_v1.request, *anyopaque) void),
    wp_single_pixel_buffer_manager_v1: std.EnumArray(single_pixel_buffer_v1.single_pixel_buffer_manager_v1.request, ?*const fn (u32, single_pixel_buffer_v1.single_pixel_buffer_manager_v1.request, *anyopaque) void),
    wp_tearing_control_manager_v1: std.EnumArray(tearing_control_v1.tearing_control_manager_v1.request, ?*const fn (u32, tearing_control_v1.tearing_control_manager_v1.request, *anyopaque) void),
    wp_tearing_control_v1: std.EnumArray(tearing_control_v1.tearing_control_v1.request, ?*const fn (u32, tearing_control_v1.tearing_control_v1.request, *anyopaque) void),
    xdg_activation_v1: std.EnumArray(xdg_activation_v1.activation_v1.request, ?*const fn (u32, xdg_activation_v1.activation_v1.request, *anyopaque) void),
    xdg_activation_token_v1: std.EnumArray(xdg_activation_v1.activation_token_v1.request, ?*const fn (u32, xdg_activation_v1.activation_token_v1.request, *anyopaque) void),
    xdg_wm_dialog_v1: std.EnumArray(xdg_dialog_v1.wm_dialog_v1.request, ?*const fn (u32, xdg_dialog_v1.wm_dialog_v1.request, *anyopaque) void),
    xdg_dialog_v1: std.EnumArray(xdg_dialog_v1.dialog_v1.request, ?*const fn (u32, xdg_dialog_v1.dialog_v1.request, *anyopaque) void),
    xdg_toplevel_drag_manager_v1: std.EnumArray(xdg_toplevel_drag_v1.toplevel_drag_manager_v1.request, ?*const fn (u32, xdg_toplevel_drag_v1.toplevel_drag_manager_v1.request, *anyopaque) void),
    xdg_toplevel_drag_v1: std.EnumArray(xdg_toplevel_drag_v1.toplevel_drag_v1.request, ?*const fn (u32, xdg_toplevel_drag_v1.toplevel_drag_v1.request, *anyopaque) void),
    xwayland_shell_v1: std.EnumArray(xwayland_shell_v1.shell_v1.request, ?*const fn (u32, xwayland_shell_v1.shell_v1.request, *anyopaque) void),
    xwayland_surface_v1: std.EnumArray(xwayland_shell_v1.surface_v1.request, ?*const fn (u32, xwayland_shell_v1.surface_v1.request, *anyopaque) void),
    ext_image_capture_source_v1: std.EnumArray(ext_image_capture_source_v1.image_capture_source_v1.request, ?*const fn (u32, ext_image_capture_source_v1.image_capture_source_v1.request, *anyopaque) void),
    ext_output_image_capture_source_manager_v1: std.EnumArray(ext_image_capture_source_v1.output_image_capture_source_manager_v1.request, ?*const fn (u32, ext_image_capture_source_v1.output_image_capture_source_manager_v1.request, *anyopaque) void),
    ext_foreign_toplevel_image_capture_source_manager_v1: std.EnumArray(ext_image_capture_source_v1.foreign_toplevel_image_capture_source_manager_v1.request, ?*const fn (u32, ext_image_capture_source_v1.foreign_toplevel_image_capture_source_manager_v1.request, *anyopaque) void),
    ext_image_copy_capture_manager_v1: std.EnumArray(ext_image_copy_capture_v1.image_copy_capture_manager_v1.request, ?*const fn (u32, ext_image_copy_capture_v1.image_copy_capture_manager_v1.request, *anyopaque) void),
    ext_image_copy_capture_session_v1: std.EnumArray(ext_image_copy_capture_v1.image_copy_capture_session_v1.request, ?*const fn (u32, ext_image_copy_capture_v1.image_copy_capture_session_v1.request, *anyopaque) void),
    ext_image_copy_capture_frame_v1: std.EnumArray(ext_image_copy_capture_v1.image_copy_capture_frame_v1.request, ?*const fn (u32, ext_image_copy_capture_v1.image_copy_capture_frame_v1.request, *anyopaque) void),
    ext_image_copy_capture_cursor_session_v1: std.EnumArray(ext_image_copy_capture_v1.image_copy_capture_cursor_session_v1.request, ?*const fn (u32, ext_image_copy_capture_v1.image_copy_capture_cursor_session_v1.request, *anyopaque) void),
    xdg_toplevel_icon_manager_v1: std.EnumArray(xdg_toplevel_icon_v1.toplevel_icon_manager_v1.request, ?*const fn (u32, xdg_toplevel_icon_v1.toplevel_icon_manager_v1.request, *anyopaque) void),
    xdg_toplevel_icon_v1: std.EnumArray(xdg_toplevel_icon_v1.toplevel_icon_v1.request, ?*const fn (u32, xdg_toplevel_icon_v1.toplevel_icon_v1.request, *anyopaque) void),
    wp_commit_timing_manager_v1: std.EnumArray(commit_timing_v1.commit_timing_manager_v1.request, ?*const fn (u32, commit_timing_v1.commit_timing_manager_v1.request, *anyopaque) void),
    wp_commit_timer_v1: std.EnumArray(commit_timing_v1.commit_timer_v1.request, ?*const fn (u32, commit_timing_v1.commit_timer_v1.request, *anyopaque) void),
    wp_fifo_manager_v1: std.EnumArray(fifo_v1.fifo_manager_v1.request, ?*const fn (u32, fifo_v1.fifo_manager_v1.request, *anyopaque) void),
    wp_fifo_v1: std.EnumArray(fifo_v1.fifo_v1.request, ?*const fn (u32, fifo_v1.fifo_v1.request, *anyopaque) void),
    xdg_system_bell_v1: std.EnumArray(xdg_system_bell_v1.system_bell_v1.request, ?*const fn (u32, xdg_system_bell_v1.system_bell_v1.request, *anyopaque) void),
    zwp_fullscreen_shell_v1: std.EnumArray(fullscreen_shell_unstable_v1.fullscreen_shell_v1.request, ?*const fn (u32, fullscreen_shell_unstable_v1.fullscreen_shell_v1.request, *anyopaque) void),
    zwp_fullscreen_shell_mode_feedback_v1: std.EnumArray(fullscreen_shell_unstable_v1.fullscreen_shell_mode_feedback_v1.request, ?*const fn (u32, fullscreen_shell_unstable_v1.fullscreen_shell_mode_feedback_v1.request, *anyopaque) void),
    zwp_idle_inhibit_manager_v1: std.EnumArray(idle_inhibit_unstable_v1.idle_inhibit_manager_v1.request, ?*const fn (u32, idle_inhibit_unstable_v1.idle_inhibit_manager_v1.request, *anyopaque) void),
    zwp_idle_inhibitor_v1: std.EnumArray(idle_inhibit_unstable_v1.idle_inhibitor_v1.request, ?*const fn (u32, idle_inhibit_unstable_v1.idle_inhibitor_v1.request, *anyopaque) void),
    zwp_input_method_context_v1: std.EnumArray(input_method_unstable_v1.input_method_context_v1.request, ?*const fn (u32, input_method_unstable_v1.input_method_context_v1.request, *anyopaque) void),
    zwp_input_method_v1: std.EnumArray(input_method_unstable_v1.input_method_v1.request, ?*const fn (u32, input_method_unstable_v1.input_method_v1.request, *anyopaque) void),
    zwp_input_panel_v1: std.EnumArray(input_method_unstable_v1.input_panel_v1.request, ?*const fn (u32, input_method_unstable_v1.input_panel_v1.request, *anyopaque) void),
    zwp_input_panel_surface_v1: std.EnumArray(input_method_unstable_v1.input_panel_surface_v1.request, ?*const fn (u32, input_method_unstable_v1.input_panel_surface_v1.request, *anyopaque) void),
    zwp_input_timestamps_manager_v1: std.EnumArray(input_timestamps_unstable_v1.input_timestamps_manager_v1.request, ?*const fn (u32, input_timestamps_unstable_v1.input_timestamps_manager_v1.request, *anyopaque) void),
    zwp_input_timestamps_v1: std.EnumArray(input_timestamps_unstable_v1.input_timestamps_v1.request, ?*const fn (u32, input_timestamps_unstable_v1.input_timestamps_v1.request, *anyopaque) void),
    zwp_keyboard_shortcuts_inhibit_manager_v1: std.EnumArray(keyboard_shortcuts_inhibit_unstable_v1.keyboard_shortcuts_inhibit_manager_v1.request, ?*const fn (u32, keyboard_shortcuts_inhibit_unstable_v1.keyboard_shortcuts_inhibit_manager_v1.request, *anyopaque) void),
    zwp_keyboard_shortcuts_inhibitor_v1: std.EnumArray(keyboard_shortcuts_inhibit_unstable_v1.keyboard_shortcuts_inhibitor_v1.request, ?*const fn (u32, keyboard_shortcuts_inhibit_unstable_v1.keyboard_shortcuts_inhibitor_v1.request, *anyopaque) void),
    zwp_linux_explicit_synchronization_v1: std.EnumArray(zwp_linux_explicit_synchronization_unstable_v1.linux_explicit_synchronization_v1.request, ?*const fn (u32, zwp_linux_explicit_synchronization_unstable_v1.linux_explicit_synchronization_v1.request, *anyopaque) void),
    zwp_linux_surface_synchronization_v1: std.EnumArray(zwp_linux_explicit_synchronization_unstable_v1.linux_surface_synchronization_v1.request, ?*const fn (u32, zwp_linux_explicit_synchronization_unstable_v1.linux_surface_synchronization_v1.request, *anyopaque) void),
    zwp_linux_buffer_release_v1: std.EnumArray(zwp_linux_explicit_synchronization_unstable_v1.linux_buffer_release_v1.request, ?*const fn (u32, zwp_linux_explicit_synchronization_unstable_v1.linux_buffer_release_v1.request, *anyopaque) void),
    zwp_pointer_constraints_v1: std.EnumArray(pointer_constraints_unstable_v1.pointer_constraints_v1.request, ?*const fn (u32, pointer_constraints_unstable_v1.pointer_constraints_v1.request, *anyopaque) void),
    zwp_locked_pointer_v1: std.EnumArray(pointer_constraints_unstable_v1.locked_pointer_v1.request, ?*const fn (u32, pointer_constraints_unstable_v1.locked_pointer_v1.request, *anyopaque) void),
    zwp_confined_pointer_v1: std.EnumArray(pointer_constraints_unstable_v1.confined_pointer_v1.request, ?*const fn (u32, pointer_constraints_unstable_v1.confined_pointer_v1.request, *anyopaque) void),
    zwp_pointer_gestures_v1: std.EnumArray(pointer_gestures_unstable_v1.pointer_gestures_v1.request, ?*const fn (u32, pointer_gestures_unstable_v1.pointer_gestures_v1.request, *anyopaque) void),
    zwp_pointer_gesture_swipe_v1: std.EnumArray(pointer_gestures_unstable_v1.pointer_gesture_swipe_v1.request, ?*const fn (u32, pointer_gestures_unstable_v1.pointer_gesture_swipe_v1.request, *anyopaque) void),
    zwp_pointer_gesture_pinch_v1: std.EnumArray(pointer_gestures_unstable_v1.pointer_gesture_pinch_v1.request, ?*const fn (u32, pointer_gestures_unstable_v1.pointer_gesture_pinch_v1.request, *anyopaque) void),
    zwp_pointer_gesture_hold_v1: std.EnumArray(pointer_gestures_unstable_v1.pointer_gesture_hold_v1.request, ?*const fn (u32, pointer_gestures_unstable_v1.pointer_gesture_hold_v1.request, *anyopaque) void),
    zwp_primary_selection_device_manager_v1: std.EnumArray(wp_primary_selection_unstable_v1.primary_selection_device_manager_v1.request, ?*const fn (u32, wp_primary_selection_unstable_v1.primary_selection_device_manager_v1.request, *anyopaque) void),
    zwp_primary_selection_device_v1: std.EnumArray(wp_primary_selection_unstable_v1.primary_selection_device_v1.request, ?*const fn (u32, wp_primary_selection_unstable_v1.primary_selection_device_v1.request, *anyopaque) void),
    zwp_primary_selection_offer_v1: std.EnumArray(wp_primary_selection_unstable_v1.primary_selection_offer_v1.request, ?*const fn (u32, wp_primary_selection_unstable_v1.primary_selection_offer_v1.request, *anyopaque) void),
    zwp_primary_selection_source_v1: std.EnumArray(wp_primary_selection_unstable_v1.primary_selection_source_v1.request, ?*const fn (u32, wp_primary_selection_unstable_v1.primary_selection_source_v1.request, *anyopaque) void),
    zwp_relative_pointer_manager_v1: std.EnumArray(relative_pointer_unstable_v1.relative_pointer_manager_v1.request, ?*const fn (u32, relative_pointer_unstable_v1.relative_pointer_manager_v1.request, *anyopaque) void),
    zwp_relative_pointer_v1: std.EnumArray(relative_pointer_unstable_v1.relative_pointer_v1.request, ?*const fn (u32, relative_pointer_unstable_v1.relative_pointer_v1.request, *anyopaque) void),
    zwp_text_input_v1: std.EnumArray(text_input_unstable_v1.text_input_v1.request, ?*const fn (u32, text_input_unstable_v1.text_input_v1.request, *anyopaque) void),
    zwp_text_input_manager_v1: std.EnumArray(text_input_unstable_v1.text_input_manager_v1.request, ?*const fn (u32, text_input_unstable_v1.text_input_manager_v1.request, *anyopaque) void),
    zwp_text_input_v3: std.EnumArray(text_input_unstable_v3.text_input_v3.request, ?*const fn (u32, text_input_unstable_v3.text_input_v3.request, *anyopaque) void),
    zwp_text_input_manager_v3: std.EnumArray(text_input_unstable_v3.text_input_manager_v3.request, ?*const fn (u32, text_input_unstable_v3.text_input_manager_v3.request, *anyopaque) void),
    zxdg_decoration_manager_v1: std.EnumArray(xdg_decoration_unstable_v1.decoration_manager_v1.request, ?*const fn (u32, xdg_decoration_unstable_v1.decoration_manager_v1.request, *anyopaque) void),
    zxdg_toplevel_decoration_v1: std.EnumArray(xdg_decoration_unstable_v1.toplevel_decoration_v1.request, ?*const fn (u32, xdg_decoration_unstable_v1.toplevel_decoration_v1.request, *anyopaque) void),
    zxdg_exporter_v1: std.EnumArray(xdg_foreign_unstable_v1.exporter_v1.request, ?*const fn (u32, xdg_foreign_unstable_v1.exporter_v1.request, *anyopaque) void),
    zxdg_importer_v1: std.EnumArray(xdg_foreign_unstable_v1.importer_v1.request, ?*const fn (u32, xdg_foreign_unstable_v1.importer_v1.request, *anyopaque) void),
    zxdg_exported_v1: std.EnumArray(xdg_foreign_unstable_v1.exported_v1.request, ?*const fn (u32, xdg_foreign_unstable_v1.exported_v1.request, *anyopaque) void),
    zxdg_imported_v1: std.EnumArray(xdg_foreign_unstable_v1.imported_v1.request, ?*const fn (u32, xdg_foreign_unstable_v1.imported_v1.request, *anyopaque) void),
    zxdg_exporter_v2: std.EnumArray(xdg_foreign_unstable_v2.exporter_v2.request, ?*const fn (u32, xdg_foreign_unstable_v2.exporter_v2.request, *anyopaque) void),
    zxdg_importer_v2: std.EnumArray(xdg_foreign_unstable_v2.importer_v2.request, ?*const fn (u32, xdg_foreign_unstable_v2.importer_v2.request, *anyopaque) void),
    zxdg_exported_v2: std.EnumArray(xdg_foreign_unstable_v2.exported_v2.request, ?*const fn (u32, xdg_foreign_unstable_v2.exported_v2.request, *anyopaque) void),
    zxdg_imported_v2: std.EnumArray(xdg_foreign_unstable_v2.imported_v2.request, ?*const fn (u32, xdg_foreign_unstable_v2.imported_v2.request, *anyopaque) void),
    zxdg_output_manager_v1: std.EnumArray(xdg_output_unstable_v1.output_manager_v1.request, ?*const fn (u32, xdg_output_unstable_v1.output_manager_v1.request, *anyopaque) void),
    zxdg_output_v1: std.EnumArray(xdg_output_unstable_v1.output_v1.request, ?*const fn (u32, xdg_output_unstable_v1.output_v1.request, *anyopaque) void),
    zwp_xwayland_keyboard_grab_manager_v1: std.EnumArray(xwayland_keyboard_grab_unstable_v1.xwayland_keyboard_grab_manager_v1.request, ?*const fn (u32, xwayland_keyboard_grab_unstable_v1.xwayland_keyboard_grab_manager_v1.request, *anyopaque) void),
    zwp_xwayland_keyboard_grab_v1: std.EnumArray(xwayland_keyboard_grab_unstable_v1.xwayland_keyboard_grab_v1.request, ?*const fn (u32, xwayland_keyboard_grab_unstable_v1.xwayland_keyboard_grab_v1.request, *anyopaque) void),
};

pub const Events = union(Interface) {
    invalid: std.EnumArray(enum {}, ?*const fn (u32, enum {}, *anyopaque) void),
    wl_display: std.EnumArray(wayland.display.event, ?*const fn (u32, wayland.display.event, *anyopaque) void),
    wl_registry: std.EnumArray(wayland.registry.event, ?*const fn (u32, wayland.registry.event, *anyopaque) void),
    wl_callback: std.EnumArray(wayland.callback.event, ?*const fn (u32, wayland.callback.event, *anyopaque) void),
    wl_compositor: std.EnumArray(wayland.compositor.event, ?*const fn (u32, wayland.compositor.event, *anyopaque) void),
    wl_shm_pool: std.EnumArray(wayland.shm_pool.event, ?*const fn (u32, wayland.shm_pool.event, *anyopaque) void),
    wl_shm: std.EnumArray(wayland.shm.event, ?*const fn (u32, wayland.shm.event, *anyopaque) void),
    wl_buffer: std.EnumArray(wayland.buffer.event, ?*const fn (u32, wayland.buffer.event, *anyopaque) void),
    wl_data_offer: std.EnumArray(wayland.data_offer.event, ?*const fn (u32, wayland.data_offer.event, *anyopaque) void),
    wl_data_source: std.EnumArray(wayland.data_source.event, ?*const fn (u32, wayland.data_source.event, *anyopaque) void),
    wl_data_device: std.EnumArray(wayland.data_device.event, ?*const fn (u32, wayland.data_device.event, *anyopaque) void),
    wl_data_device_manager: std.EnumArray(wayland.data_device_manager.event, ?*const fn (u32, wayland.data_device_manager.event, *anyopaque) void),
    wl_shell: std.EnumArray(wayland.shell.event, ?*const fn (u32, wayland.shell.event, *anyopaque) void),
    wl_shell_surface: std.EnumArray(wayland.shell_surface.event, ?*const fn (u32, wayland.shell_surface.event, *anyopaque) void),
    wl_surface: std.EnumArray(wayland.surface.event, ?*const fn (u32, wayland.surface.event, *anyopaque) void),
    wl_seat: std.EnumArray(wayland.seat.event, ?*const fn (u32, wayland.seat.event, *anyopaque) void),
    wl_pointer: std.EnumArray(wayland.pointer.event, ?*const fn (u32, wayland.pointer.event, *anyopaque) void),
    wl_keyboard: std.EnumArray(wayland.keyboard.event, ?*const fn (u32, wayland.keyboard.event, *anyopaque) void),
    wl_touch: std.EnumArray(wayland.touch.event, ?*const fn (u32, wayland.touch.event, *anyopaque) void),
    wl_output: std.EnumArray(wayland.output.event, ?*const fn (u32, wayland.output.event, *anyopaque) void),
    wl_region: std.EnumArray(wayland.region.event, ?*const fn (u32, wayland.region.event, *anyopaque) void),
    wl_subcompositor: std.EnumArray(wayland.subcompositor.event, ?*const fn (u32, wayland.subcompositor.event, *anyopaque) void),
    wl_subsurface: std.EnumArray(wayland.subsurface.event, ?*const fn (u32, wayland.subsurface.event, *anyopaque) void),
    zwp_linux_dmabuf_v1: std.EnumArray(linux_dmabuf_v1.linux_dmabuf_v1.event, ?*const fn (u32, linux_dmabuf_v1.linux_dmabuf_v1.event, *anyopaque) void),
    zwp_linux_buffer_params_v1: std.EnumArray(linux_dmabuf_v1.linux_buffer_params_v1.event, ?*const fn (u32, linux_dmabuf_v1.linux_buffer_params_v1.event, *anyopaque) void),
    zwp_linux_dmabuf_feedback_v1: std.EnumArray(linux_dmabuf_v1.linux_dmabuf_feedback_v1.event, ?*const fn (u32, linux_dmabuf_v1.linux_dmabuf_feedback_v1.event, *anyopaque) void),
    wp_presentation: std.EnumArray(presentation_time.presentation.event, ?*const fn (u32, presentation_time.presentation.event, *anyopaque) void),
    wp_presentation_feedback: std.EnumArray(presentation_time.presentation_feedback.event, ?*const fn (u32, presentation_time.presentation_feedback.event, *anyopaque) void),
    zwp_tablet_manager_v2: std.EnumArray(tablet_v2.tablet_manager_v2.event, ?*const fn (u32, tablet_v2.tablet_manager_v2.event, *anyopaque) void),
    zwp_tablet_seat_v2: std.EnumArray(tablet_v2.tablet_seat_v2.event, ?*const fn (u32, tablet_v2.tablet_seat_v2.event, *anyopaque) void),
    zwp_tablet_tool_v2: std.EnumArray(tablet_v2.tablet_tool_v2.event, ?*const fn (u32, tablet_v2.tablet_tool_v2.event, *anyopaque) void),
    zwp_tablet_v2: std.EnumArray(tablet_v2.tablet_v2.event, ?*const fn (u32, tablet_v2.tablet_v2.event, *anyopaque) void),
    zwp_tablet_pad_ring_v2: std.EnumArray(tablet_v2.tablet_pad_ring_v2.event, ?*const fn (u32, tablet_v2.tablet_pad_ring_v2.event, *anyopaque) void),
    zwp_tablet_pad_strip_v2: std.EnumArray(tablet_v2.tablet_pad_strip_v2.event, ?*const fn (u32, tablet_v2.tablet_pad_strip_v2.event, *anyopaque) void),
    zwp_tablet_pad_group_v2: std.EnumArray(tablet_v2.tablet_pad_group_v2.event, ?*const fn (u32, tablet_v2.tablet_pad_group_v2.event, *anyopaque) void),
    zwp_tablet_pad_v2: std.EnumArray(tablet_v2.tablet_pad_v2.event, ?*const fn (u32, tablet_v2.tablet_pad_v2.event, *anyopaque) void),
    wp_viewporter: std.EnumArray(viewporter.viewporter.event, ?*const fn (u32, viewporter.viewporter.event, *anyopaque) void),
    wp_viewport: std.EnumArray(viewporter.viewport.event, ?*const fn (u32, viewporter.viewport.event, *anyopaque) void),
    xdg_wm_base: std.EnumArray(xdg_shell.wm_base.event, ?*const fn (u32, xdg_shell.wm_base.event, *anyopaque) void),
    xdg_positioner: std.EnumArray(xdg_shell.positioner.event, ?*const fn (u32, xdg_shell.positioner.event, *anyopaque) void),
    xdg_surface: std.EnumArray(xdg_shell.surface.event, ?*const fn (u32, xdg_shell.surface.event, *anyopaque) void),
    xdg_toplevel: std.EnumArray(xdg_shell.toplevel.event, ?*const fn (u32, xdg_shell.toplevel.event, *anyopaque) void),
    xdg_popup: std.EnumArray(xdg_shell.popup.event, ?*const fn (u32, xdg_shell.popup.event, *anyopaque) void),
    wp_alpha_modifier_v1: std.EnumArray(alpha_modifier_v1.alpha_modifier_v1.event, ?*const fn (u32, alpha_modifier_v1.alpha_modifier_v1.event, *anyopaque) void),
    wp_alpha_modifier_surface_v1: std.EnumArray(alpha_modifier_v1.alpha_modifier_surface_v1.event, ?*const fn (u32, alpha_modifier_v1.alpha_modifier_surface_v1.event, *anyopaque) void),
    wp_content_type_manager_v1: std.EnumArray(content_type_v1.content_type_manager_v1.event, ?*const fn (u32, content_type_v1.content_type_manager_v1.event, *anyopaque) void),
    wp_content_type_v1: std.EnumArray(content_type_v1.content_type_v1.event, ?*const fn (u32, content_type_v1.content_type_v1.event, *anyopaque) void),
    wp_cursor_shape_manager_v1: std.EnumArray(cursor_shape_v1.cursor_shape_manager_v1.event, ?*const fn (u32, cursor_shape_v1.cursor_shape_manager_v1.event, *anyopaque) void),
    wp_cursor_shape_device_v1: std.EnumArray(cursor_shape_v1.cursor_shape_device_v1.event, ?*const fn (u32, cursor_shape_v1.cursor_shape_device_v1.event, *anyopaque) void),
    wp_drm_lease_device_v1: std.EnumArray(drm_lease_v1.drm_lease_device_v1.event, ?*const fn (u32, drm_lease_v1.drm_lease_device_v1.event, *anyopaque) void),
    wp_drm_lease_connector_v1: std.EnumArray(drm_lease_v1.drm_lease_connector_v1.event, ?*const fn (u32, drm_lease_v1.drm_lease_connector_v1.event, *anyopaque) void),
    wp_drm_lease_request_v1: std.EnumArray(drm_lease_v1.drm_lease_request_v1.event, ?*const fn (u32, drm_lease_v1.drm_lease_request_v1.event, *anyopaque) void),
    wp_drm_lease_v1: std.EnumArray(drm_lease_v1.drm_lease_v1.event, ?*const fn (u32, drm_lease_v1.drm_lease_v1.event, *anyopaque) void),
    ext_foreign_toplevel_list_v1: std.EnumArray(ext_foreign_toplevel_list_v1.foreign_toplevel_list_v1.event, ?*const fn (u32, ext_foreign_toplevel_list_v1.foreign_toplevel_list_v1.event, *anyopaque) void),
    ext_foreign_toplevel_handle_v1: std.EnumArray(ext_foreign_toplevel_list_v1.foreign_toplevel_handle_v1.event, ?*const fn (u32, ext_foreign_toplevel_list_v1.foreign_toplevel_handle_v1.event, *anyopaque) void),
    ext_idle_notifier_v1: std.EnumArray(ext_idle_notify_v1.idle_notifier_v1.event, ?*const fn (u32, ext_idle_notify_v1.idle_notifier_v1.event, *anyopaque) void),
    ext_idle_notification_v1: std.EnumArray(ext_idle_notify_v1.idle_notification_v1.event, ?*const fn (u32, ext_idle_notify_v1.idle_notification_v1.event, *anyopaque) void),
    ext_session_lock_manager_v1: std.EnumArray(ext_session_lock_v1.session_lock_manager_v1.event, ?*const fn (u32, ext_session_lock_v1.session_lock_manager_v1.event, *anyopaque) void),
    ext_session_lock_v1: std.EnumArray(ext_session_lock_v1.session_lock_v1.event, ?*const fn (u32, ext_session_lock_v1.session_lock_v1.event, *anyopaque) void),
    ext_session_lock_surface_v1: std.EnumArray(ext_session_lock_v1.session_lock_surface_v1.event, ?*const fn (u32, ext_session_lock_v1.session_lock_surface_v1.event, *anyopaque) void),
    ext_transient_seat_manager_v1: std.EnumArray(ext_transient_seat_v1.transient_seat_manager_v1.event, ?*const fn (u32, ext_transient_seat_v1.transient_seat_manager_v1.event, *anyopaque) void),
    ext_transient_seat_v1: std.EnumArray(ext_transient_seat_v1.transient_seat_v1.event, ?*const fn (u32, ext_transient_seat_v1.transient_seat_v1.event, *anyopaque) void),
    wp_fractional_scale_manager_v1: std.EnumArray(fractional_scale_v1.fractional_scale_manager_v1.event, ?*const fn (u32, fractional_scale_v1.fractional_scale_manager_v1.event, *anyopaque) void),
    wp_fractional_scale_v1: std.EnumArray(fractional_scale_v1.fractional_scale_v1.event, ?*const fn (u32, fractional_scale_v1.fractional_scale_v1.event, *anyopaque) void),
    wp_linux_drm_syncobj_manager_v1: std.EnumArray(linux_drm_syncobj_v1.linux_drm_syncobj_manager_v1.event, ?*const fn (u32, linux_drm_syncobj_v1.linux_drm_syncobj_manager_v1.event, *anyopaque) void),
    wp_linux_drm_syncobj_timeline_v1: std.EnumArray(linux_drm_syncobj_v1.linux_drm_syncobj_timeline_v1.event, ?*const fn (u32, linux_drm_syncobj_v1.linux_drm_syncobj_timeline_v1.event, *anyopaque) void),
    wp_linux_drm_syncobj_surface_v1: std.EnumArray(linux_drm_syncobj_v1.linux_drm_syncobj_surface_v1.event, ?*const fn (u32, linux_drm_syncobj_v1.linux_drm_syncobj_surface_v1.event, *anyopaque) void),
    wp_security_context_manager_v1: std.EnumArray(security_context_v1.security_context_manager_v1.event, ?*const fn (u32, security_context_v1.security_context_manager_v1.event, *anyopaque) void),
    wp_security_context_v1: std.EnumArray(security_context_v1.security_context_v1.event, ?*const fn (u32, security_context_v1.security_context_v1.event, *anyopaque) void),
    wp_single_pixel_buffer_manager_v1: std.EnumArray(single_pixel_buffer_v1.single_pixel_buffer_manager_v1.event, ?*const fn (u32, single_pixel_buffer_v1.single_pixel_buffer_manager_v1.event, *anyopaque) void),
    wp_tearing_control_manager_v1: std.EnumArray(tearing_control_v1.tearing_control_manager_v1.event, ?*const fn (u32, tearing_control_v1.tearing_control_manager_v1.event, *anyopaque) void),
    wp_tearing_control_v1: std.EnumArray(tearing_control_v1.tearing_control_v1.event, ?*const fn (u32, tearing_control_v1.tearing_control_v1.event, *anyopaque) void),
    xdg_activation_v1: std.EnumArray(xdg_activation_v1.activation_v1.event, ?*const fn (u32, xdg_activation_v1.activation_v1.event, *anyopaque) void),
    xdg_activation_token_v1: std.EnumArray(xdg_activation_v1.activation_token_v1.event, ?*const fn (u32, xdg_activation_v1.activation_token_v1.event, *anyopaque) void),
    xdg_wm_dialog_v1: std.EnumArray(xdg_dialog_v1.wm_dialog_v1.event, ?*const fn (u32, xdg_dialog_v1.wm_dialog_v1.event, *anyopaque) void),
    xdg_dialog_v1: std.EnumArray(xdg_dialog_v1.dialog_v1.event, ?*const fn (u32, xdg_dialog_v1.dialog_v1.event, *anyopaque) void),
    xdg_toplevel_drag_manager_v1: std.EnumArray(xdg_toplevel_drag_v1.toplevel_drag_manager_v1.event, ?*const fn (u32, xdg_toplevel_drag_v1.toplevel_drag_manager_v1.event, *anyopaque) void),
    xdg_toplevel_drag_v1: std.EnumArray(xdg_toplevel_drag_v1.toplevel_drag_v1.event, ?*const fn (u32, xdg_toplevel_drag_v1.toplevel_drag_v1.event, *anyopaque) void),
    xwayland_shell_v1: std.EnumArray(xwayland_shell_v1.shell_v1.event, ?*const fn (u32, xwayland_shell_v1.shell_v1.event, *anyopaque) void),
    xwayland_surface_v1: std.EnumArray(xwayland_shell_v1.surface_v1.event, ?*const fn (u32, xwayland_shell_v1.surface_v1.event, *anyopaque) void),
    ext_image_capture_source_v1: std.EnumArray(ext_image_capture_source_v1.image_capture_source_v1.event, ?*const fn (u32, ext_image_capture_source_v1.image_capture_source_v1.event, *anyopaque) void),
    ext_output_image_capture_source_manager_v1: std.EnumArray(ext_image_capture_source_v1.output_image_capture_source_manager_v1.event, ?*const fn (u32, ext_image_capture_source_v1.output_image_capture_source_manager_v1.event, *anyopaque) void),
    ext_foreign_toplevel_image_capture_source_manager_v1: std.EnumArray(ext_image_capture_source_v1.foreign_toplevel_image_capture_source_manager_v1.event, ?*const fn (u32, ext_image_capture_source_v1.foreign_toplevel_image_capture_source_manager_v1.event, *anyopaque) void),
    ext_image_copy_capture_manager_v1: std.EnumArray(ext_image_copy_capture_v1.image_copy_capture_manager_v1.event, ?*const fn (u32, ext_image_copy_capture_v1.image_copy_capture_manager_v1.event, *anyopaque) void),
    ext_image_copy_capture_session_v1: std.EnumArray(ext_image_copy_capture_v1.image_copy_capture_session_v1.event, ?*const fn (u32, ext_image_copy_capture_v1.image_copy_capture_session_v1.event, *anyopaque) void),
    ext_image_copy_capture_frame_v1: std.EnumArray(ext_image_copy_capture_v1.image_copy_capture_frame_v1.event, ?*const fn (u32, ext_image_copy_capture_v1.image_copy_capture_frame_v1.event, *anyopaque) void),
    ext_image_copy_capture_cursor_session_v1: std.EnumArray(ext_image_copy_capture_v1.image_copy_capture_cursor_session_v1.event, ?*const fn (u32, ext_image_copy_capture_v1.image_copy_capture_cursor_session_v1.event, *anyopaque) void),
    xdg_toplevel_icon_manager_v1: std.EnumArray(xdg_toplevel_icon_v1.toplevel_icon_manager_v1.event, ?*const fn (u32, xdg_toplevel_icon_v1.toplevel_icon_manager_v1.event, *anyopaque) void),
    xdg_toplevel_icon_v1: std.EnumArray(xdg_toplevel_icon_v1.toplevel_icon_v1.event, ?*const fn (u32, xdg_toplevel_icon_v1.toplevel_icon_v1.event, *anyopaque) void),
    wp_commit_timing_manager_v1: std.EnumArray(commit_timing_v1.commit_timing_manager_v1.event, ?*const fn (u32, commit_timing_v1.commit_timing_manager_v1.event, *anyopaque) void),
    wp_commit_timer_v1: std.EnumArray(commit_timing_v1.commit_timer_v1.event, ?*const fn (u32, commit_timing_v1.commit_timer_v1.event, *anyopaque) void),
    wp_fifo_manager_v1: std.EnumArray(fifo_v1.fifo_manager_v1.event, ?*const fn (u32, fifo_v1.fifo_manager_v1.event, *anyopaque) void),
    wp_fifo_v1: std.EnumArray(fifo_v1.fifo_v1.event, ?*const fn (u32, fifo_v1.fifo_v1.event, *anyopaque) void),
    xdg_system_bell_v1: std.EnumArray(xdg_system_bell_v1.system_bell_v1.event, ?*const fn (u32, xdg_system_bell_v1.system_bell_v1.event, *anyopaque) void),
    zwp_fullscreen_shell_v1: std.EnumArray(fullscreen_shell_unstable_v1.fullscreen_shell_v1.event, ?*const fn (u32, fullscreen_shell_unstable_v1.fullscreen_shell_v1.event, *anyopaque) void),
    zwp_fullscreen_shell_mode_feedback_v1: std.EnumArray(fullscreen_shell_unstable_v1.fullscreen_shell_mode_feedback_v1.event, ?*const fn (u32, fullscreen_shell_unstable_v1.fullscreen_shell_mode_feedback_v1.event, *anyopaque) void),
    zwp_idle_inhibit_manager_v1: std.EnumArray(idle_inhibit_unstable_v1.idle_inhibit_manager_v1.event, ?*const fn (u32, idle_inhibit_unstable_v1.idle_inhibit_manager_v1.event, *anyopaque) void),
    zwp_idle_inhibitor_v1: std.EnumArray(idle_inhibit_unstable_v1.idle_inhibitor_v1.event, ?*const fn (u32, idle_inhibit_unstable_v1.idle_inhibitor_v1.event, *anyopaque) void),
    zwp_input_method_context_v1: std.EnumArray(input_method_unstable_v1.input_method_context_v1.event, ?*const fn (u32, input_method_unstable_v1.input_method_context_v1.event, *anyopaque) void),
    zwp_input_method_v1: std.EnumArray(input_method_unstable_v1.input_method_v1.event, ?*const fn (u32, input_method_unstable_v1.input_method_v1.event, *anyopaque) void),
    zwp_input_panel_v1: std.EnumArray(input_method_unstable_v1.input_panel_v1.event, ?*const fn (u32, input_method_unstable_v1.input_panel_v1.event, *anyopaque) void),
    zwp_input_panel_surface_v1: std.EnumArray(input_method_unstable_v1.input_panel_surface_v1.event, ?*const fn (u32, input_method_unstable_v1.input_panel_surface_v1.event, *anyopaque) void),
    zwp_input_timestamps_manager_v1: std.EnumArray(input_timestamps_unstable_v1.input_timestamps_manager_v1.event, ?*const fn (u32, input_timestamps_unstable_v1.input_timestamps_manager_v1.event, *anyopaque) void),
    zwp_input_timestamps_v1: std.EnumArray(input_timestamps_unstable_v1.input_timestamps_v1.event, ?*const fn (u32, input_timestamps_unstable_v1.input_timestamps_v1.event, *anyopaque) void),
    zwp_keyboard_shortcuts_inhibit_manager_v1: std.EnumArray(keyboard_shortcuts_inhibit_unstable_v1.keyboard_shortcuts_inhibit_manager_v1.event, ?*const fn (u32, keyboard_shortcuts_inhibit_unstable_v1.keyboard_shortcuts_inhibit_manager_v1.event, *anyopaque) void),
    zwp_keyboard_shortcuts_inhibitor_v1: std.EnumArray(keyboard_shortcuts_inhibit_unstable_v1.keyboard_shortcuts_inhibitor_v1.event, ?*const fn (u32, keyboard_shortcuts_inhibit_unstable_v1.keyboard_shortcuts_inhibitor_v1.event, *anyopaque) void),
    zwp_linux_explicit_synchronization_v1: std.EnumArray(zwp_linux_explicit_synchronization_unstable_v1.linux_explicit_synchronization_v1.event, ?*const fn (u32, zwp_linux_explicit_synchronization_unstable_v1.linux_explicit_synchronization_v1.event, *anyopaque) void),
    zwp_linux_surface_synchronization_v1: std.EnumArray(zwp_linux_explicit_synchronization_unstable_v1.linux_surface_synchronization_v1.event, ?*const fn (u32, zwp_linux_explicit_synchronization_unstable_v1.linux_surface_synchronization_v1.event, *anyopaque) void),
    zwp_linux_buffer_release_v1: std.EnumArray(zwp_linux_explicit_synchronization_unstable_v1.linux_buffer_release_v1.event, ?*const fn (u32, zwp_linux_explicit_synchronization_unstable_v1.linux_buffer_release_v1.event, *anyopaque) void),
    zwp_pointer_constraints_v1: std.EnumArray(pointer_constraints_unstable_v1.pointer_constraints_v1.event, ?*const fn (u32, pointer_constraints_unstable_v1.pointer_constraints_v1.event, *anyopaque) void),
    zwp_locked_pointer_v1: std.EnumArray(pointer_constraints_unstable_v1.locked_pointer_v1.event, ?*const fn (u32, pointer_constraints_unstable_v1.locked_pointer_v1.event, *anyopaque) void),
    zwp_confined_pointer_v1: std.EnumArray(pointer_constraints_unstable_v1.confined_pointer_v1.event, ?*const fn (u32, pointer_constraints_unstable_v1.confined_pointer_v1.event, *anyopaque) void),
    zwp_pointer_gestures_v1: std.EnumArray(pointer_gestures_unstable_v1.pointer_gestures_v1.event, ?*const fn (u32, pointer_gestures_unstable_v1.pointer_gestures_v1.event, *anyopaque) void),
    zwp_pointer_gesture_swipe_v1: std.EnumArray(pointer_gestures_unstable_v1.pointer_gesture_swipe_v1.event, ?*const fn (u32, pointer_gestures_unstable_v1.pointer_gesture_swipe_v1.event, *anyopaque) void),
    zwp_pointer_gesture_pinch_v1: std.EnumArray(pointer_gestures_unstable_v1.pointer_gesture_pinch_v1.event, ?*const fn (u32, pointer_gestures_unstable_v1.pointer_gesture_pinch_v1.event, *anyopaque) void),
    zwp_pointer_gesture_hold_v1: std.EnumArray(pointer_gestures_unstable_v1.pointer_gesture_hold_v1.event, ?*const fn (u32, pointer_gestures_unstable_v1.pointer_gesture_hold_v1.event, *anyopaque) void),
    zwp_primary_selection_device_manager_v1: std.EnumArray(wp_primary_selection_unstable_v1.primary_selection_device_manager_v1.event, ?*const fn (u32, wp_primary_selection_unstable_v1.primary_selection_device_manager_v1.event, *anyopaque) void),
    zwp_primary_selection_device_v1: std.EnumArray(wp_primary_selection_unstable_v1.primary_selection_device_v1.event, ?*const fn (u32, wp_primary_selection_unstable_v1.primary_selection_device_v1.event, *anyopaque) void),
    zwp_primary_selection_offer_v1: std.EnumArray(wp_primary_selection_unstable_v1.primary_selection_offer_v1.event, ?*const fn (u32, wp_primary_selection_unstable_v1.primary_selection_offer_v1.event, *anyopaque) void),
    zwp_primary_selection_source_v1: std.EnumArray(wp_primary_selection_unstable_v1.primary_selection_source_v1.event, ?*const fn (u32, wp_primary_selection_unstable_v1.primary_selection_source_v1.event, *anyopaque) void),
    zwp_relative_pointer_manager_v1: std.EnumArray(relative_pointer_unstable_v1.relative_pointer_manager_v1.event, ?*const fn (u32, relative_pointer_unstable_v1.relative_pointer_manager_v1.event, *anyopaque) void),
    zwp_relative_pointer_v1: std.EnumArray(relative_pointer_unstable_v1.relative_pointer_v1.event, ?*const fn (u32, relative_pointer_unstable_v1.relative_pointer_v1.event, *anyopaque) void),
    zwp_text_input_v1: std.EnumArray(text_input_unstable_v1.text_input_v1.event, ?*const fn (u32, text_input_unstable_v1.text_input_v1.event, *anyopaque) void),
    zwp_text_input_manager_v1: std.EnumArray(text_input_unstable_v1.text_input_manager_v1.event, ?*const fn (u32, text_input_unstable_v1.text_input_manager_v1.event, *anyopaque) void),
    zwp_text_input_v3: std.EnumArray(text_input_unstable_v3.text_input_v3.event, ?*const fn (u32, text_input_unstable_v3.text_input_v3.event, *anyopaque) void),
    zwp_text_input_manager_v3: std.EnumArray(text_input_unstable_v3.text_input_manager_v3.event, ?*const fn (u32, text_input_unstable_v3.text_input_manager_v3.event, *anyopaque) void),
    zxdg_decoration_manager_v1: std.EnumArray(xdg_decoration_unstable_v1.decoration_manager_v1.event, ?*const fn (u32, xdg_decoration_unstable_v1.decoration_manager_v1.event, *anyopaque) void),
    zxdg_toplevel_decoration_v1: std.EnumArray(xdg_decoration_unstable_v1.toplevel_decoration_v1.event, ?*const fn (u32, xdg_decoration_unstable_v1.toplevel_decoration_v1.event, *anyopaque) void),
    zxdg_exporter_v1: std.EnumArray(xdg_foreign_unstable_v1.exporter_v1.event, ?*const fn (u32, xdg_foreign_unstable_v1.exporter_v1.event, *anyopaque) void),
    zxdg_importer_v1: std.EnumArray(xdg_foreign_unstable_v1.importer_v1.event, ?*const fn (u32, xdg_foreign_unstable_v1.importer_v1.event, *anyopaque) void),
    zxdg_exported_v1: std.EnumArray(xdg_foreign_unstable_v1.exported_v1.event, ?*const fn (u32, xdg_foreign_unstable_v1.exported_v1.event, *anyopaque) void),
    zxdg_imported_v1: std.EnumArray(xdg_foreign_unstable_v1.imported_v1.event, ?*const fn (u32, xdg_foreign_unstable_v1.imported_v1.event, *anyopaque) void),
    zxdg_exporter_v2: std.EnumArray(xdg_foreign_unstable_v2.exporter_v2.event, ?*const fn (u32, xdg_foreign_unstable_v2.exporter_v2.event, *anyopaque) void),
    zxdg_importer_v2: std.EnumArray(xdg_foreign_unstable_v2.importer_v2.event, ?*const fn (u32, xdg_foreign_unstable_v2.importer_v2.event, *anyopaque) void),
    zxdg_exported_v2: std.EnumArray(xdg_foreign_unstable_v2.exported_v2.event, ?*const fn (u32, xdg_foreign_unstable_v2.exported_v2.event, *anyopaque) void),
    zxdg_imported_v2: std.EnumArray(xdg_foreign_unstable_v2.imported_v2.event, ?*const fn (u32, xdg_foreign_unstable_v2.imported_v2.event, *anyopaque) void),
    zxdg_output_manager_v1: std.EnumArray(xdg_output_unstable_v1.output_manager_v1.event, ?*const fn (u32, xdg_output_unstable_v1.output_manager_v1.event, *anyopaque) void),
    zxdg_output_v1: std.EnumArray(xdg_output_unstable_v1.output_v1.event, ?*const fn (u32, xdg_output_unstable_v1.output_v1.event, *anyopaque) void),
    zwp_xwayland_keyboard_grab_manager_v1: std.EnumArray(xwayland_keyboard_grab_unstable_v1.xwayland_keyboard_grab_manager_v1.event, ?*const fn (u32, xwayland_keyboard_grab_unstable_v1.xwayland_keyboard_grab_manager_v1.event, *anyopaque) void),
    zwp_xwayland_keyboard_grab_v1: std.EnumArray(xwayland_keyboard_grab_unstable_v1.xwayland_keyboard_grab_v1.event, ?*const fn (u32, xwayland_keyboard_grab_unstable_v1.xwayland_keyboard_grab_v1.event, *anyopaque) void),
};
